### ISSUE TITLE
Website changes tracking issue

### ISSUE THREAD

**Issue by Lyeeedar** [flyway/flywaydb.org#213]
Issue to track outsiding docs pages I think we need

- [x] Schema history table description
- [x] How to add things to the classpath
- [x] Find out what FLYWAY_IGNORE_INVALID_MIGRATION_NAMES is supposed to be
- [x] Find out why no env variable support for validateMigrationNaming
- [x] Add cross links in repair to config params
- [x] Find all cases across the site of config params being referenced and change them to links
- [x] Add index.md page
- [x] Add links in sidebar (maybe only after collapse support)
- [x] Update endpoint pages to link to config param list
- [x] Go through blogs and add links from config to blog they are exampled
- [ ] Flesh out validate docs, and link to config params
- [x] Link to config params from each command page
- [ ] PLACEHOLDERS_PROPERTY_PREFIX and JDBC_PROPERTIES_PREFIX has odd usage
